### ISSUE TITLE
some bugs in testing "1. A basic walkthrough of 3k PBMC cells starting from a pre-computed Seurat object."

### ISSUE THREAD

**Issue by ChickenWangSY** [yanwu2014/swne#11]
Hi, 
     when I was testing the first walkthrough by the test data, I met a error at the step "Runs the SWNE embedding" : 
     `swne.embedding <- EmbedSWNE(nmf.scores, snn, alpha.exp = alpha.exp, snn.exp = snn.exp,n_pull = n_pull, dist.use = "IC")`
     the error information is **Error in get_factor_coords(H.smooth, method = proj.method, pca.red = pca.red,  :  Distance must be one of: pearson, IC, cosine, euclidean**
     then, I used my own data to test the tutorial ,but got the same error. And I didn't change any steps in the tutorial.
    could you please give me some advice about it ? 
    Much thanks !
     

> 

>

**Comment by ChickenWangSY** [comment]
emmmmm ,  when I tried the other tutorial ,I found  a parameter in `EmbedSWNE` called ` dist.use`. When I set it in `cosine`, the tutorial is OK. When I set it in `IC`, it called error. 
In fact, I don't really understand the principle in it.

**Comment by yanwu2014** [comment]
Thanks for the heads up, it should be fixed!

So the `dist.use` is setting the metric used to embed the factors. Different metrics, like cosine distance or information coefficient (IC), will have different advantages and disadvantages. We find that setting `dist.use = cosine` works very well in most cases.

Let me know if that helps!

**Comment by yanwu2014** [comment]
Closing this thread if there are no more comments!
