### ISSUE TITLE
Unlisted dependencies

### ISSUE THREAD

**Issue by darrentyson** [yanwu2014/swne#17]
Thanks for providing the code. Hoping to get in running soon. But, I ran into some issues while trying to install. Many dependencies are not listed anywhere. I found them one-by-one in the resultant error messages over multiple `swne`installation attempts. I had to install each of the following (and I may have missed one or more during the process):

```
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene", version = "3.8")
BiocManager::install("org.Hs.eg.db")
devtools::install_github("aertslab/RcisTarget")
devtools::install_github("aertslab/AUCell")
devtools::install_github("aertslab/cisTopic")
```
Also, getting the following warnings many times during installation process.

```
In file included from swne_cpp_funcs.cpp:2:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include/RcppEigenForward.h:39:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include/unsupported/Eigen/Polynomials:135:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
```

Did actually install, even with these warnings, however.

**Comment by yanwu2014** [comment]
Thanks for the heads up, and sorry for the inconvenience! Most of those dependencies seem to be from making SWNE compatible with cisTopic. I've pushed some updates that add the cisTopic dependencies to remote, and restructured the code to remove the bioconductor dependencies.

Not entirely sure what's causing the warnings but I'll look into it

**Comment by jlmelville** [comment]
In case it's helpful, I just installed swne and in addtion to cisTopic, I had to also install Seurat.
