### ISSUE TITLE
SWNE plotting on Tabular Data

### ISSUE THREAD

**Issue by Saini-96** [yanwu2014/swne#19]
Hi Team,

I have followed the steps for plotting SWNE on genome data. Now i want to plot SWNE on my custom dataset which is nothing but Structured Tabular data.
So is there any plugin or module for plotting SWNE on my custom dataset?
Please help me out with this.

Thanks in advance

**Comment by yanwu2014** [comment]
Hi Saini, sorry for the late reply. Can you give me an example of what your structured tabular data looks like?

**Comment by Saini-96** [comment]
Hi Yanwu,

Like my dataset has more than 13 cloumns, where some of the columns
contains string values, some of the coulmns contains Dates & some of the
coulmns has numerical value.
It is Salesforce dataset.
Where we will find out the customer late payment related analysis.

Thanks & Regards,
Rahul Saini

**Comment by yanwu2014** [comment]
Ah unfortunately SWNE will only work on numerical data, it doesn't work for categorical variables

**Comment by Saini-96** [comment]
Ok got it but didn't find any plugin or module by making use of which I can
use SWNE on numerical data.
I saw your GitHub page where SWNE was implemented for geonom data.
So please help me out on how to implement SWNE on numerical data.

Regards,
Rahul Saini

**Comment by yanwu2014** [comment]
Gotcha, so if you want to run SWNE on a numerical matrix you can use the `RunSWNE` wrapper function on a sparse or dense matrix.

Let me know if that helps!

**Comment by Saini-96** [comment]
Ok will try & let you know
One more thing we don't require cisTopic or serut object what you used for
genomics data.
Simply we have to fetch numerical dataset & run RunSWNE on that, am I right?

**Comment by yanwu2014** [comment]
Yes you can use RunSWNE on any numerical matrix.

**Comment by yanwu2014** [comment]
Closing this for now, let me know if you run into any additional issues!
