### ISSUE TITLE
Offical Seurat 3.0 Tutorial

### ISSUE THREAD

**Issue by MediciPrime** [yanwu2014/swne#20]
Thank you for creating this awesome tool.  I have two questions, one related to Github/SWNE and one just for SWNE:
1.  Would you be able to create a tutorial for using SWNE with a Seurat 3.0 object?
2.  I recall that a Single-cell Webinar for SWNE had taken place on Friday April 26th.  Do you happen to have a recording for that webinar?

**Comment by yanwu2014** [comment]
Glad to hear you're enjoying the tool! So I'm in the process of updating the code to work with Seurat 3.0 right now, it should be done by the end of next week. And it looks the SWNE webinar was just posted online now: https://www.youtube.com/watch?v=dv6vae3dr2Y

**Comment by MediciPrime** [comment]
That is great news!!  Can't wait for SWNE to be updated for Seurat 3.0.  Also thank you for sending the link to the webinar, I really appreciate it.
