### ISSUE TITLE
Bringing a seurat v3 object into SWNE

### ISSUE THREAD

**Issue by hgb1111** [yanwu2014/swne#22]
Hi, I have used SWNE before to study an object that I generated in Seurat v2. 

However, with a Seurat version 3 object, I am unsure how to extract the necessary information to run a SWNE analysis. 

Previously, I was able to run:
 
```
se.obj <- OBJECT

se.obj@raw.data <- FilterData(as(se.obj@raw.data, "dgCMatrix"), min.samples.frac = 0.0025, 
                              min.nonzero.features = 200, trim = 0.0025)

norm.counts <- ExtractNormCounts(se.obj, obj.type = "seurat", rescale = T, rescale.method = "log", batch = NULL) 
```

and then proceed with my swne analysis. 

However, I am unsure how to bring this information out of a Seurat v3 object. 

Thoughts?

**Comment by yanwu2014** [comment]
Hi,

Yes so the Seurat V3 object interface is different. The equivalent command would be something like:

```
AssayData(se.obj, slot = "counts") <- FilterData(AssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
```

Let me know if that works! Also the full list of updated Seurat V3 commands is here: https://satijalab.org/seurat/essential_commands.html. FYI if you have Seurat V2 objects you'll need to remake them to use Seurat V3 commands.

Let me know if that works!

**Comment by yanwu2014** [comment]
Closing this issue if there aren't any more questions!
