### ISSUE TITLE
Seurat V3 Workflow

### ISSUE THREAD

**Issue by hgb1111** [yanwu2014/swne#23]
I ran the code you sent 

`AssayData(se.obj, slot = "counts") <- FilterData(AssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
`

and got the following error 

`Error in AssayData(se.obj, slot = "counts") : 
  could not find function "AssayData"`

I have loaded swne, Seurat, Matrix, ggplot2. what package isnt loaded?

**Comment by yanwu2014** [comment]
Ah sorry it should be `GetAssayData` instead of `AssayData`. Let me know if that works!

**Comment by hgb1111** [comment]
`AssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
Error in AssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj,  : 
  could not find function "AssayData<-"
> GetAssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
Error in GetAssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj,  : 
  could not find function "GetAssayData<-"`

**Comment by yanwu2014** [comment]
Are you sure you have Seurat V3 installed? Also it should be: 
```
SetAssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
```

**Comment by hgb1111** [comment]
> SetAssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
Error in SetAssayData(se.obj, slot = "counts") <- FilterData(GetAssayData(se.obj,  : 
  could not find function "SetAssayData<-"
> packageVersion("Seurat")
[1] ‘3.0.2’

**Comment by hgb1111** [comment]
I have also tried running through the Gene Expression Quickstart with Seurat, but run into an error where the "RunSWNE" does not seem to be compatible with a seurat v3 object. 


```
## Load object
load("/path/Ma_Vasc_6_res0.75.Robj")
obj <- Ma_Vasc_6_res0.75

## Extract clusters
clusters <- obj$seurat_clusters

## Select genes to embed
genes.embed <- c("Aplnr", "Apln", "Cryab", "Gata5", "Pi16")

## Run SWNE
swne.embedding <- RunSWNE(obj, k = 16, genes.embed = genes.embed)

Error in UseMethod("RunSWNE") : 
  no applicable method for 'RunSWNE' applied to an object of class "Seurat"

packageVersion("Seurat")
# ‘3.0.2’
packageVersion("swne")
# ‘0.2.21’

```

**Comment by yanwu2014** [comment]
Ahh sorry you're right. For the filtering it should be something more like:

```
counts <- FilterData(GetAssayData(se.obj, slot = "counts"), min.samples.frac = 0.0025, min.nonzero.features = 200, trim = 0.0025)
se.obj <- SetAssayData(se.obj, slot = "counts", new.data = counts)
```

**Comment by yanwu2014** [comment]
Oh so the latest version of swne should be 0.5.6. Can you try reinstalling it and see if `RunSWNE` works then?

**Comment by hgb1111** [comment]
Certainly, is that only available for R version 3.6.1? I just tried installing on 3.5.1 and 3.5.3 and neither worked. 

Thanks!

**Comment by yanwu2014** [comment]
Ah sorry yeah I built it on R3.6 so I think >= R3.6.1 is necessary for installation

**Comment by hgb1111** [comment]
I updated R, but I am somehow still getting the same error: 

install.packages("SWNE")
Warning in install.packages :
  package ‘SWNE’ is not available (for R version 3.6.1)

**Comment by hgb1111** [comment]
I updated to R version 3.6.1 (2019-07-05) -- "Action of the Toes" but am unfortunately still encountering the same error

```
install.packages("swne")
Warning in install.packages :
  package ‘swne’ is not available (for R version 3.6.1)
```

**Comment by yanwu2014** [comment]
`swne` is not on CRAN so you can't use install.packages. You can install it with devtools using the instructions on this github page

**Comment by hgb1111** [comment]
Ahh, that fixed the issue - my mistake for not seeing that earlier. I was able to work through swne with a seurat v3 object. 

Thanks!

**Comment by yanwu2014** [comment]
Great! Let me know if you have any other issues!
