### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by xuebaliang** [yanwu2014/swne#27]
hello, recently I failed to install the swne package on the linux server. Thus can you supply it using offline form ".tar.gz"??? In this way I can use "R CMD INSTALL" to install it. Thanks.

**Comment by yanwu2014** [comment]
Hi! Can you let me know what error you're having? Otherwise I think you can clone the directory locally: `git clone git@github.com:yanwu2014/swne.git` and install it locally that way

**Comment by xuebaliang** [comment]
Thanks for your reply.  I have tried three ways to install swne, but all of them failed.
chenliang@ubuntu:~$ git clone git@github.com:yanwu2014/swne.git
Cloning into 'swne'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

> library("devtools")
Loading required package: usethis
> devtools::install_github("yanwu2014/swne")
Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10001 milliseconds
> devtools::install_local("/data/chenliang/R/offline_R_package/swne-master.zip")
Error: Failed to install 'swne-master.zip' from local:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds

**Comment by xuebaliang** [comment]
I suggest that you can pack all codes in .tar.gz and develop it in CRAN or bioconductor. It is very convenient for users.

**Comment by yanwu2014** [comment]
Ah it seems like some type of connection issue with github then. I'll work on making a tarball ASAP, and yes the eventual plan is to move to CRAN. Thanks for the heads up!

**Comment by mr-september** [comment]
I, too, cannot install via devtools.
```
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS"=TRUE)
devtools::install_github("linxihui/NNLM")
devtools::install_github("yanwu2014/swne")
```
Error:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'jsonlite'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'swne'
* removing 'C:/Users/username/Documents/R/win-library/4.0/swne
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\username\Documents\R\win-library\4.0\00LOCK\jsonlite\libs\x64\jsonlite.dll to C:\Users\username\Documents\R\win-library\4.0\jsonlite\libs\x64\jsonlite.dll: Permission denied
2: In i.p(...) :
  installation of package ‘C:/Users/username/AppData/Local/Temp/RtmpcvJteA/file498c5ac16713/swne_0.6.16.tar.gz’ had non-zero exit status
```

Note: I have tried to force (re-?)install jsonlite:
```
install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')
```

This does not solve the above Error 
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'jsonlite'
```

**Comment by yanwu2014** [comment]
Hmm I can't seem reproduce this error either. Are you installing SWNE from a clean R/RStudio session (with no packages) loaded? Also it might help to try installing the devtools version: devtools::install_github("jeroen/jsonlite")

I also just added jsonlite as an explicit dependency to see if that helps. Let me know if it's still not installing?

**Comment by mr-september** [comment]
> Hmm I can't seem reproduce this error either. Are you installing SWNE from a clean R/RStudio session (with no packages) loaded? Also it might help to try installing the devtools version: devtools::install_github("jeroen/jsonlite")
> 
> I also just added jsonlite as an explicit dependency to see if that helps. Let me know if it's still not installing?

I think that did the trick! I attempted again today and it installed without problems. Thank you!
