### ISSUE TITLE
Error running RunSWNE

### ISSUE THREAD

**Issue by HyacintViolet** [yanwu2014/swne#29]
While running SWNE Seurat pipeline I received the following error:

`> swne.embedding <- RunSWNE(cells.seurat, k = 16, genes.embed = genes.embed, sample.groups = cell.clusters)`
`Error in ExtractNormCounts(object, obj.type = "seurat", rescale = F, rescale.method = "log",  : `
` unused argument (rescale = F)`

It seems as if `RunSWNE()` calls `ExtractNormCount()` with argument `rescale = F` whereas `rescale` is not defined.

**Comment by yanwu2014** [comment]
Ah yes that's a bug from updating `ExtractNormCounts` without updating `RunSWNE`. Should be fixed now, thanks for the heads up! Let me know if there's still an issue!

**Comment by HyacintViolet** [comment]
Works perfectly now, thanks!
