### ISSUE TITLE
Seurat- SCTransform compatibility?

### ISSUE THREAD

**Issue by mr-september** [yanwu2014/swne#30]
Seems similar to #25.

Typical PBMC 5K data, preprocessed and clustered in Seurat (and native SCTransform).

FindNeighours done, UMAP generated. But
`swne.embedding <- RunSWNE(data_transcripts_seurat, k = 20)`
```
calculating variance fit ... using gam [1] "4800 variable genes to use"
Computing nearest neighbor graph
Computing SNN
Error in as(object@graphs$RNA_snn, "dgCMatrix") : 
  no method or default for coercing “NULL” to “dgCMatrix”
In addition: Warning message:
In pf(exp(df$res), n.obs, n.obs, lower.tail = F, log.p = F) : NaNs produced
```

Checking my seurat object, it turns out there's no `RNA_snn`, but instead there's `SCT_nn` and `SCT_snn`. 

Would this error be solved by making SWNE look for `object@graphs$SCT_snn` instead? If so, how?

**Comment by yanwu2014** [comment]
Hi! Sorry for the late reply, was working on a manuscript deadline. Thanks for pointing this out, I've updated the `RunSWNE` function to look for `object@graphs$SCT_nn` when the DefaultAssay is SCT, which it is automatically set to after running SCTransform. Let me know if that works!

**Comment by mr-september** [comment]
Hi, thank you! I forgot about this but just tried it again today and it works flawlessly now!

Just another suggestion: in your Readme, maybe recommend `remotes::install()` instead of `devtools::install_github()`, the former has much less dependencies and often work where the latter gives errors.

**Comment by yanwu2014** [comment]
Thanks for the suggestion, I just updated to using remotes! Yeah I've noticed devtools does not handle dependencies well too

**Comment by mr-september** [comment]
Hi @yanwu2014, apologies for the mistake, I double checked and realised it's `remotes::install_github()`, not `remotes::install()`
