### ISSUE TITLE
SWNE plotting of samples subsets

### ISSUE THREAD

**Issue by terooatt** [yanwu2014/swne#4]
I have merged different samples using seurat and then run SWNE. What would be the best way to show a subset (i.e. different samples) in the SWNE plot, while maintaining the overall structure of the SWNE plot. thanks

**Comment by yanwu2014** [comment]
You should be able to use the `samples.plot` parameter in `PlotSWNE` to plot a subset of the samples. Just specify the names of the samples you'd like to plot. Let me know if that works for you!

**Comment by terooatt** [comment]
Sorry for the late reply. It worked well.
Cheers!
