### ISSUE TITLE
Change in behaviour (output) of FindNumFactors

### ISSUE THREAD

**Issue by TomKellyGenetics** [yanwu2014/swne#8]
There a change in the output format of FindNumFactors. It is not longer a list nor does it compute a k value. This change has not been documented and the version number has not be incremented to indicate that there is a change. This has caused my existing pipeline which calls this function and the output k parameter to give an error an abort.

Please ensure that functions are backwards-compatible and produce the same output variables. To change the behaviour of a function drastically, please deprecate the existing version and create a function with a different name. This will cause less disruption for users with existing code that calls these functions.

**Comment by yanwu2014** [comment]
Ah sorry I'll keep that in mind. Thanks for the heads up!

**Comment by TomKellyGenetics** [comment]
Sorry `FindNumFactors` now returns a list (as it did before) but it has an error if 'do.plot = TRUE`. This change may have affected `PlotFactorSelection`.

**Comment by yanwu2014** [comment]
Closing this thread if there are no more issues!
