### ISSUE TITLE
Formatting issue in error message

### ISSUE THREAD

**Issue by TomKellyGenetics** [yanwu2014/swne#9]
Formatting issue in error message when calling EmbedSWNE with `dist.metric = "correlation"`:

  > swne_embedding <- EmbedSWNE(nmf.scores, snn, alpha.exp = alpha.exp, snn.exp = snn.exp,
    +                               n_pull = n_pull, dist.use = dist.metric)
    Error in get_factor_coords(H.smooth, method = proj.method, pca.red = pca.red,  : 
      Distance must be one of: pearsonDistance must be one of: ICDistance must be one of: 
      cosineDistance must be one of: euclidean

**Comment by yanwu2014** [comment]
Thanks! Should be fixed now!
